const AvayaChatConfig = {
  // json Methods
  jsonMethodFileTransfer: 'newAgentFileTransfer',
  jsonMethodPing: 'pong',
  jsonMethodRequestChat: 'requestChat',
  jsonMethodRequestCloseConversation: 'closeConversation',
  jsonMethodRequestIsTyping: 'isTyping',
  jsonMethodRequestNewMessage: 'newMessage',
  jsonMethodRequestNewParticipant: 'newParticipant',
  jsonMethodRequestParticipantLeave: 'participantLeave',

  // message types
  messageTypeAck: 'acknowledgement',
  messageTypeError: 'error',
  messageTypeNotification: 'notification',

  // write response class
  writeResponseClassChatbot: 'chatbot',
  writeResponseClassResponse: 'response',
  writeResponseClassSent: 'sent',
  writeResponseClassSystem: 'system',

  // console meesages
  chatAvailableMsg:
    'The chat is available. Your estimated wait time is {0} minutes. Click the "Live Chat" tab to open the chat',
  chatNotAvailableMsg: 'The chat is not currently available. Please try again later',
  chatPossibleMsg: 'The chat is available. Click the "Live Chat" tab to open the chat.',
  noAgentsAvailableMsg: 'No agents are currently available. Please try again later',

  // variables
  apiEndpointsDomain: '',
  routePointIdentifier: 'Sales_prod',
  activeAgentTypeOut: null,
  agentTypingTimeout: 5000,
  attributes: ['Country.US', 'Language.English', 'LOB.Sales', 'Concern.Drive'],
  customData: {},
  leaseTime: 0,
  locale: 'en-US',
  maxNumberOfRetries: 200,
  maxWaitTime: 600,
  minAgentCount: 1,
  minWaitTime: 0,
  newMessageText: '{0} ({1}): {2}',
  noFieldLabel: 'No',
  notifyOfBarge: true,
  notifyOfObserve: false,
  onModalOpen: () => {},
  onModalClose: () => {},
  passiveAgentTypeOut: null,
  pingTimer: 5000,
  formDetails: {
    chatLiteForm: {},
    preEngagementForm: {},
    disablePrefilledInputs: false,
  },
  bypassChatBubble: false,
  priority: 5,
  refreshTimeoutSeconds: 300,
  resetTimer: 5000,
  retryInterval: 3000,
  supervisorTypeOut: null,
  suppressChatbotPresence: false,
  timeBetweenMsgs: 10000,
  typeOfPage: 'Sales',
  workflowType: '',
  analyticsIsOn: false,
  sessionWasTransferred: false,
  statusCardShowTime: 10000,
  namesMaxCharCount: 50,
  isChatLite: false,
  isTriagePreChat: false,
  isEnergyPage: false,
  isWindowMinimized: false,
  capturedChatImpression: false,
  defaultWaitTime: 1,
  sendSubjectMessage: false,
  autoInitiate: false,
  modifiedChatInit: false,

  initializers: {
    InputPlaceHolder: 'Type message',
    AutomatedMessageBody: 'Please connect me with a Tesla expert.',
    MessageCanvasTrayButton: 'START NEW CHAT',
    MessageCanvasTrayHeader: 'Thanks for chatting with us!',
    MessageCanvasTrayParagraph: 'If you have any more questions please reach out to us again.',
    FieldValidationInvalidEmail: 'Please provide a valid email address',
    statusCardSuccessHeader: 'Thank you!',
    statusCardSuccessText: 'We will contact you soon.',
    statusCardErrorHeader: 'Something went wrong!',
    statusCardErrorText: 'Please try again later.',
    agentJoinedMessage: 'An agent has joined the chat',
    agentLeftMessage: 'An agent has left the chat',
    attemptingToReconnectText: 'Attempting to reconnect...',
    chatbotTransferNotification: 'Transferring to a live agent, please remain in the chat',
    closeRequestText: 'Close request sent',
    closedForMaintenanceText:
      'Contact centre is shutting down for maintenance. Please try again later',
    connectionClosedText: 'Connection closed, chat has ended',
    connectionErrorText: 'A connection error has occurred. Check the console for more details',
    errorOccurredText: 'Error code {0} occurred ({1})',
    footerButtonText: 'Send',
    fileTransferMessageText: '{0} transferred a file ({1}) at {2}. Please visit {3} to download it',
    headerText: 'Chat',
    reloadingPageText: 'Transferring chat session from previous page or tab.',
    requeueNotificationText: 'Re-queuing chat, please remain in the chat',
    tooltipButtonText: 'Start Chat',
    tooltipQuestionText: 'Have a question?',
    transferNotificationText: 'Transferring to another service, please remain in the chat',
    transferToUserText: 'Transferring to another agent, please remain in the chat',
    formErrorMessageIsRequired: '{0} is a required property',
    formErrorMessageInvalid: '{0} is invalid',
    formErrorMessageMaxLength: 'Maximum length of {0} is {1} characters',
    unableToReconnectText: 'Unable to reconnect, chat has ended',
    successfulReconnectionText: 'Successfully reconnected',
    chatSessionTransferred: 'Chat was opened in another tab, continue conversation there',
    headerSubtext: 'Chat With Us',
    optionalField: 'Optional',
    routeCancelText: 'No suitable agents could be found',
    questionCenterHeader: 'Question Center',
    teslaAdvisor: 'Tesla Advisor',
    endChatScreenMessage: 'End Chat?',
    endChatScreenContinue: 'No',
    endChatScreenEnd: 'Yes',
    chatEndMessageMain: 'Thanks for Chatting With Us',
    chatEndMessageAdditional: 'If you have additional questions,\n reach out to us again',
    chatEstimatedWaitTime:
      'We are connecting you to an agent. The next agent will be available {0}.',
    ariaLabelLoading: 'Loading',
    ariaLabelChatButton: 'Chat button',
    ariaLabelCloseModal: 'Close modal',
    ariaLabelMessageArea: 'Message text area',
    ariaLabelSendButton: 'Send button',
    ariaLabelMinimizeModal: 'Minimize modal',
    ariaLabelBackButton: 'Back button',
  },

  preEngagementConfig: {
    fields: [
      {
        type: 'InputItem',
        label: 'First name',
        attributes: {
          name: 'firstName',
          type: 'text',
          required: true,
          placeholder: 'Enter your first name',
        },
      },
      {
        type: 'InputItem',
        label: 'Last name',
        attributes: {
          name: 'lastName',
          type: 'text',
          required: false,
          placeholder: 'Enter your last name',
        },
      },
      {
        type: 'InputItem',
        label: 'Email address',
        attributes: {
          name: 'email',
          type: 'email',
          required: true,
          placeholder: 'Enter your email address',
        },
      },
      {
        type: 'InputItem',
        label: 'Phone',
        attributes: {
          name: 'phoneNumber',
          type: 'text',
          required: true,
          placeholder: 'Enter your phone number',
        },
      },
      {
        type: 'InputItem',
        label: 'Zip Code',
        attributes: {
          name: 'postalCode',
          type: 'text',
          required: true,
          placeholder: 'Enter your zip code',
        },
      },
      {
        type: 'SelectItem',
        label: 'Get Tesla Updates',
        options: [
          { label: 'Yes', value: 'Yes', selected: true },
          { label: 'No', value: 'No', selected: false },
        ],
        attributes: { name: 'getUpdates', required: true },
      },
    ],
    description: 'Provide your information',
    submitLabel: 'Start chat',
  },

  triageConfig: {
    chooseTopic: 'Choose Your Topic',
    chooseTopicSubtext: 'Tell us more and our customer support team will help you find the answers',
    chooseOptions: 'Select from the below options',
    teslaProducts: {
      vehicle: 'Vehicle',
      energy: 'Energy Products',
      'account-support': 'Tesla Account Support',
      'live-agent': 'Chat with a Live Agent',
    },

    teslaProductsSubTopics: {
      vehicle: {
        'test-drive': 'Test Drive',
        'trade-in': 'Trade-In',
        inventory: 'Inventory',
        'vehicle-place-order': 'Placing an order',
        'vehicle-upcoming-delivery': 'Upcoming Delivery',
        'vehicle-service-support': 'Service and Support',
      },
      energy: {
        'solar-roof': 'Solar Roof',
        'solar-panels': 'Solar Panels',
        'energy-place-order': 'Placing an Order',
        'energy-service-support': 'Service and Support',
      },
    },
    energySubTopics: ['Solar Roof', 'Solar Panels', 'Placing an Order', 'Service and Support'],
    vehicleDeliveryHeading: 'Upcoming Delivery',
    vehicleDeliveryDesription:
      'Go to the Tesla App for delivery timing updates and to learn about your new vehicle',
    vehicleDeliveryLoginLinkText: 'Go to Account',
    // eslint-disable-next-line no-restricted-globals
    vehicleDeliveryLoginLink: 'https://ts.la/app',
    additionalDeliveryHeading: 'Additional Resources',
    additionalDeliveryResources: {
      'Prepare For Delivery': '/support/delivery-day',
      'What to Expect on Delivery Day': '/support/taking-delivery',
      'After Taking Delivery': '/support/after-taking-delivery',
    },
    cantFindAnswer: "Can't Find Your Answer?",
    needMoreAssistance: 'I Still Need Help',
    vehicleServiceSupport: 'Service and Support',
    topicSupportSubHeading: 'Below are the most common answers',
    vehicleOwnershipLinks: {
      'Software Updates': '/support/software-updates',
      'Service Visits': '/support/service-visits',
      'Road Trips': '/trips',
      Supercharging: '/support/supercharging',
      'Full Self-Driving Subscriptions': '/support/full-self-driving-subscriptions',
      'Tesla App': '/support/tesla-app',
      Connectivity: '/support/connectivity',
      'Account Support': '/support/account-support',
    },
    // eslint-disable-next-line no-restricted-globals
    vehicleOwnershipSupportHelpLink: `https://auth.tesla.com/oauth2/v1/authorize?redirect_uri=${location.protocol}//${location.hostname}/teslaaccount/owner-xp/auth/callback&response_type=code&client_id=ownership&scope=offline_access%20email&audience=https%3A%2F%2Fownership.tesla.com%2F`,
    energyProductSupport: 'Service And Support',
    energyProductSupportLinks: {
      'Tesla Account': '/contactus?issue=energyProductSupport&issueSubcategory=accountBilling',
      Billing: '/contactus?issue=energyProductSupport&issueSubcategory=accountBilling',
      Contract: '/contactus?issue=energyProductSupport&issueSubcategory=accountBilling',
      'Maintenance & Troubleshooting':
        '/contactus/troubleshooting?troubleshootingGuide=diagnoseProblem',
      Scheduling:
        '/contactus/?issue=energyProductSupport&issueSubcategory=maintenanceTroubleshooting',
      'Tesla App': '/support/tesla-app',
      'Mobile App': '/contactus?issue=energyProductSupport&issueSubcategory=accountBilling',
      'Removal & Reinstallation':
        'https://forms.office.com/pages/responsepage.aspx?id=9MUmkNCGn0u9ObfU0PtGdMOmHsmMfdVDurtXFX-pEnJUMVZSRTQ3NjZNNlU4VVQwM0tPRUJTOTVKSC4u&web=1&wdLOR=c19B3730A-E4AE-E741-833C-A67BEC1C9039',
    },
    // eslint-disable-next-line no-restricted-globals
    energySupportHelpLink: `https://auth.tesla.com/oauth2/v1/authorize?redirect_uri=${location.protocol}//${location.hostname}/teslaaccount/owner-xp/auth/callback&response_type=code&client_id=ownership`,
    teslaAccountSupport: 'Tesla Account Support',
    teslaAccountSupportLinks: {
      'Password Reset': '/support/account-support#basic-account-support',
      'Create New Account': '/support/account-support#basic-account-support',
      'Add or Remove Products': '/support/account-support#add-remove-products',
      'Car Access': '/support/account-support#car-access',
      'Account Security': '/support/account-support#account-security',
    },
    // eslint-disable-next-line no-restricted-globals
    teslaAccountSupportHelpLink: `https://auth.tesla.com/oauth2/v1/authorize?redirect_uri=${location.protocol}//${location.hostname}/teslaaccount/owner-xp/auth/callback&response_type=code&client_id=ownership&scope=offline_access%20email&audience=https%3A%2F%2Fownership.tesla.com%2F`,
    backButton: 'Back',
  },

  callBackFormConfig: {
    description:
      'There are no agents currently available. Please enter your contact information and we will get back to you.',
    disclaimer:
      'By clicking "Request a Callback" I agree to be contacted at the number provided and understand these calls or texts may use computer-assisted dialing or pre-recorded messages. This consent is not a condition of purchase.',
    fields: [
      {
        attributes: {
          name: 'firstName',
          placeholder: 'Enter your first name',
          required: true,
          type: 'text',
        },
        label: 'First Name',
        type: 'InputItem',
      },
      {
        attributes: {
          name: 'lastName',
          placeholder: 'Enter your last name',
          required: true,
          type: 'text',
        },
        label: 'Last Name',
        type: 'InputItem',
      },
      {
        attributes: {
          name: 'email',
          placeholder: 'Enter your email address',
          required: true,
          type: 'email',
        },
        label: 'Email',
        type: 'InputItem',
      },
      {
        attributes: {
          name: 'phoneNumber',
          placeholder: 'Enter your phone number',
          required: true,
          type: 'text',
        },
        label: 'Phone',
        type: 'InputItem',
      },
      {
        attributes: {
          name: 'postalCode',
          placeholder: 'Enter your zip code',
          required: true,
          type: 'text',
        },
        label: 'Zip Code',
        type: 'InputItem',
      },
      {
        attributes: {
          name: 'productInterested',
          required: true,
        },
        label: 'Product Interest',
        options: ['Model S', 'Model 3', 'Model X', 'Model Y', 'Solar Panels', 'Solar Roof'],
        type: 'CheckboxItem',
      },
    ],
    submitLabel: 'Request a Callback',
  },
};
export default AvayaChatConfig;
